spring:
  h2:
    console:
      enabled: true
      path: /console

  datasource:
    url: jdbc:h2:file:C:/Users/pondr/Desktop/GitHub/Notes/db

  jpa:
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        globally_quoted_identifiers=true:
